spring.application.name=spring-boot-security-jwt
# ===============================
# Server Configuration
# ===============================
server.port=8081
server.servlet.context-path=/api
# ===============================
# Spring Datasource (MySQL example)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/jwt_db
spring.datasource.username=root
spring.datasource.password=root1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===============================
# JPA / Hibernate Configuration
# ===============================
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# ===============================
# File Upload (Optional)
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# ===============================
# JWT / Token Settings (Optional)
# ===============================
jwt.secret.key=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5emFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6
jwt.token.expire.validity=86400000


# 1 day in milliseconds
# ===============================
# Internationalization (Optional)
# ===============================
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.devtools.restart.enabled=false
springdoc.swagger-ui.enabled=true
# application-test.properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html

# ===============================
# CORS / Cross-Origin (Optional)
# ===============================
# spring.web.cors.allowed-origins=http://localhost:3000


